In [14]:
import numpy as np
import tensorflow as tf

In [5]:
x = np.zeros((3,4))
print(x)
print("..")
print((x == 1).astype(float))

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
..
[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


In [9]:
y = np.zeros((12,2))
y[:,0] = (x == 0).astype(float).reshape(12)

In [10]:
print(y)

[[ 1.  0.]
 [ 1.  0.]
 [ 1.  0.]
 [ 1.  0.]
 [ 1.  0.]
 [ 1.  0.]
 [ 1.  0.]
 [ 1.  0.]
 [ 1.  0.]
 [ 1.  0.]
 [ 1.  0.]
 [ 1.  0.]]


In [11]:
print(y[3][0])

1.0


In [12]:
print(y[3][1])

0.0


In [13]:
ret = np.zeros((12,4))
ret[:,0] = np.ones(12)
print(ret)

[[ 1.  0.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 1.  0.  0.  0.]]


In [35]:
uw = tf.Variable(3.)
x = np.ones((3,4))
y = uw*x
print(y)

Tensor("mul_6:0", shape=(3, 4), dtype=float32)


In [36]:
sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init)

In [37]:
print(sess.run(y))

[[ 3.  3.  3.  3.]
 [ 3.  3.  3.  3.]
 [ 3.  3.  3.  3.]]


In [39]:
x = np.arange(9).reshape((3,3))
z = x[:,0]
print(x)
print(z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 3 6]
